addons:
  postgresql: "9.4"
services:
  - postgresql
sudo: required
language: python
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install make libenchant1c2a postgresql-contrib-9.4
  - psql -U postgres -c "ALTER ROLE postgres PASSWORD '$TEMPO_DB_PASSWORD';"
  - sudo service postgresql restart
  - sudo pip install -U pip
  - sudo pip install .[postgresql]
  - pip install tox==2.1.1 coveralls
env:
  global:
    - TEMPO_DB_HOST=localhost
    - TEMPO_DB_PORT=5432
    - TEMPO_DB_USER=postgres
    - TEMPO_DB_PASSWORD=secret
    - TEMPO_DB_NAME=test
  matrix:
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py3-django17
    - TOX_ENV=py3-django18
    - TOX_ENV=py32-django17
    - TOX_ENV=py32-django18
    - TOX_ENV=py33-django17
    - TOX_ENV=py33-django18
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-rest_framework3
    - TOX_ENV=py27-rest_framework31
    - TOX_ENV=py27-rest_framework32
    - TOX_ENV=py3-rest_framework3
    - TOX_ENV=py3-rest_framework31
    - TOX_ENV=py3-rest_framework32
    - TOX_ENV=py32-rest_framework3
    - TOX_ENV=py32-rest_framework31
    - TOX_ENV=py32-rest_framework32
    - TOX_ENV=py33-rest_framework3
    - TOX_ENV=py33-rest_framework31
    - TOX_ENV=py33-rest_framework32
    - TOX_ENV=py34-rest_framework3
    - TOX_ENV=py34-rest_framework31
    - TOX_ENV=py34-rest_framework32
    - TOX_ENV=pep8
    - TOX_ENV=pylint
    - TOX_ENV=docs
script:
  - tox -e $TOX_ENV -v
after_success:
  coveralls
