sudo: required
language: python
addons:
  postgresql: "9.4"
before_script:
  - psql -c "CREATE ROLE dev WITH LOGIN CREATEDB PASSWORD 'dev';" -U postgres
  - psql -c "CREATE DATABASE dev
             WITH OWNER dev
             ENCODING 'UTF8'
             LC_COLLATE = 'en_US.UTF-8'
             LC_CTYPE = 'en_US.UTF-8'
             TEMPLATE template0;" -U postgres
install:
  - pip install tox==1.9.2
env:
  - TOX_ENV=py27
  - TOX_ENV=py3
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
script:
  - tox -e $TOX_ENV -v
